//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusLogicEvents.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventNotification
    {
        public int Id { get; set; }
        public int EventNotificationId { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.Guid> ProcessGuid { get; set; }
    }
}
