//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusLogicEvents.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public int Id { get; set; }
        public string Recipients { get; set; }
        public string Sender { get; set; }
        public DateTime DateSent { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool FailedSending { get; set; }
    }
}
